
-- test123
INSERT INTO THIRAVIYUM_USER (USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, MOD_USER, MOD_DATE) VALUES ('test@test.com', '$2a$10$mH9xEK7cpzsd3xBMCLUWOONHzfbfafemX2DSoGvU3g0ddQPGXYtqW', 'First', 'Last', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_USER (USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, MOD_USER, MOD_DATE) VALUES ('test2@test.com', '$2a$10$mH9xEK7cpzsd3xBMCLUWOONHzfbfafemX2DSoGvU3g0ddQPGXYtqW', 'First2', 'Last2', 'System', CURRENT_TIMESTAMP);


INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2010-06-15', 2010, 'Salary', 3000.00, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2010-12-15', 2010, 'Salary', 3377.41, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2011-04-30', 2011, 'Salary', 3377.40, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2012-03-15', 2012, 'Salary', 3377.39, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2012-06-30', 2012, 'Salary', 3377.41, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2012-09-15', 2012, 'Salary', 3377.39, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2012-12-29', 2012, 'Salary', 3377.41, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2013-02-15', 2013, 'Salary', 3752.40, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2013-05-30', 2013, 'Salary', 3752.39, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2013-08-15', 2013, 'Salary', 3752.41, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2013-11-30', 2013, 'Salary', 3752.39, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2014-01-31', 2014, 'Salary', 3840.50, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2014-06-30', 2014, 'Salary', 3758.36, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2014-08-14', 2014, 'Salary', 3802.76, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2015-01-31', 2015, 'Salary', 3754.44, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2015-04-15', 2015, 'Salary', 3754.44, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2015-07-28', 2015, 'Salary', 3754.44, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2015-10-15', 2015, 'Salary', 3856.36, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2016-01-15', 2016, 'Salary', 3754.44, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_CREDIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, SOURCE, AMOUNT, COMMENT, CREDIT_USER, MOD_USER, MOD_DATE) VALUES	('2016-03-15', 2016, 'Salary', 3754.44, '',	'test@test.com', 'System', CURRENT_TIMESTAMP);


INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2010-07-13',	2010, 1000, 46.59, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2010-11-05',	2010, 3400,	45.85, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2011-10-17',	2011, 3500,	44.03, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2011-12-16',	2011, 4800,	44.76, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2011-02-02',	2011, 3500,	44.94, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2012-03-30',	2012, 1000, 43.96, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2012-05-09',	2012, 3000,	44.57, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2012-05-15',	2012, 2500,	44.55, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2013-05-27',	2013, 2000,	44.51, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2013-06-03',	2013, 3000,	44.35, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2013-06-05',	2013, 2500,	44.31, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2014-07-29',	2014, 3000,	43.96, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2014-09-05',	2014, 2500,	46.52, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2015-10-07',	2015, 3000,	48.69, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);
INSERT INTO THIRAVIYUM_DEBIT (EFFECTIVE_DATE, EFFECTIVE_YEAR, AMOUNT, EXCHANGE_RATE, COMMENT, DEBIT_USER, MOD_USER, MOD_DATE) VALUES ('2015-11-02',	2015, 2000,	48.71, null, 'test@test.com', 'System', CURRENT_TIMESTAMP);